version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: meuplano_mongodb
    ports:
      - "27017:27017"
    volumes:
      - dados_mongo:/data/db
    networks:
      - rede_meuplano

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: meuplano_backend
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
      - MONGO_URL=mongodb://mongodb:27017/meuplano_ai
      - AI_API_URL=https://generativelanguage.googleapis.com/v1beta/openai/chat/completions
      - AI_MODEL=gemini-2.0-flash
      - AI_API_KEY=${AI_API_KEY}
    depends_on:
      - mongodb
    networks:
      - rede_meuplano

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: meuplano_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3333
    depends_on:
      - backend
    networks:
      - rede_meuplano

volumes:
  dados_mongo:

networks:
  rede_meuplano:
    driver: bridge